export const menuAssets = {
  googleIcon: null,
  closeStrokeOne: null,
  closeStrokeTwo: null,
  loginArrowOuter: null,
  loginArrowInner: null,
  loginArrowStem: null,
  divider: null,
  iconHome: null,
  iconCalendar: null,
  iconScissors: null,
  iconMustache: null,
  iconRazor: null,
  iconEyebrow: null,
  iconTowel: null,
  iconShampoo: null,
};
