export const menuAssets: Record<string, import('react-native').ImageSourcePropType | undefined> = {
  googleIcon: undefined,
  closeStrokeOne: undefined,
  closeStrokeTwo: undefined,
  loginArrowOuter: undefined,
  loginArrowInner: undefined,
  loginArrowStem: undefined,
  divider: undefined,
  iconHome: undefined,
  iconCalendar: undefined,
  iconScissors: undefined,
  iconMustache: undefined,
  iconRazor: undefined,
  iconEyebrow: undefined,
  iconTowel: undefined,
  iconShampoo: undefined,
};
