import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlayPressable: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  screen: {
    flex: 1,
    backgroundColor: '#000000',
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(20, 21, 24, 0.5)',
  },
  container: {
    marginLeft: 40,
    backgroundColor: '#141518',
    paddingVertical: 24,
    minHeight: '100%',
  },
  containerDimmed: {
    opacity: 0.5,
  },
  header: {
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    fontSize: 18,
    color: '#FFFFFF',
    fontFamily: 'Nunito_700Bold',
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconButtonSquare: {
    width: 'auto',
    height: 36,
    color: '#FFFFFF',
    fontSize: 20,
    fontFamily: 'Nunito_700Bold',
    fontWeight: 700,
    paddingHorizontal: 10,
    lineHeight: 24,
    textAlign: 'center',
    borderRadius: 10,
    backgroundColor: '#8162FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeIcon: {
    width: 20,
    height: 20,
  },
  loginRow: {
    marginTop: 24,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  loginText: {
    fontSize: 18,
    color: '#FFFFFF',
    fontFamily: 'Nunito_700Bold',
  },
  divider: {
    marginTop: 24,
    height: 1,
    backgroundColor: '#26272B',
  },
  menuGroup: {
    marginTop: 24,
    paddingHorizontal: 20,
    gap: 4,
  },
  menuButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 82,
  },
  menuButtonActive: {
    backgroundColor: '#8162FF',
  },
  menuIcon: {
    width: 16,
    height: 16,
  },
  menuLabel: {
    fontSize: 14,
    color: '#FFFFFF',
    fontFamily: 'Nunito_400Regular',
  },
  loginIconWrap: {
    width: 20,
    height: 20,
  },
  loginArrowOuter: {
    position: 'absolute',
    top: '12.5%',
    left: '62.5%',
    right: '12.5%',
    bottom: '12.5%',
  },
  loginArrowInner: {
    position: 'absolute',
    top: '29.17%',
    left: '41.67%',
    right: '37.5%',
    bottom: '29.17%',
  },
  loginArrowStem: {
    position: 'absolute',
    top: '50%',
    left: '12.5%',
    right: '37.5%',
    bottom: '50%',
  },
  closeLineOne: {
    position: 'absolute',
    top: '25%',
    left: '25%',
    right: '25%',
    bottom: '25%',
  },
  closeLineTwo: {
    position: 'absolute',
    top: '25%',
    left: '25%',
    right: '25%',
    bottom: '25%',
  },
  dialogOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dialogBackdrop: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  dialogCard: {
    width: 318,
    backgroundColor: '#141518',
    borderRadius: 10,
    padding: 20,
    gap: 20,
  },
  dialogTextGroup: {
    gap: 8,
    alignItems: 'center',
  },
  dialogTitle: {
    fontSize: 16,
    color: '#FFFFFF',
    fontFamily: 'Nunito_700Bold',
    textAlign: 'center',
  },
  dialogSubtitle: {
    fontSize: 14,
    color: '#838896',
    fontFamily: 'Nunito_400Regular',
    textAlign: 'center',
  },
  dialogButton: {
    borderWidth: 1,
    borderColor: '#26272B',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  dialogButtonDisabled: {
    opacity: 0.65,
  },
  dialogButtonText: {
    fontSize: 14,
    color: '#FFFFFF',
    fontFamily: 'Nunito_700Bold',
  },
  dialogErrorText: {
    fontSize: 13,
    color: '#FF7D7D',
    fontFamily: 'Nunito_400Regular',
    textAlign: 'center',
  },
  dialogGoogleIcon: {
    width: 16,
    height: 16,
  },
  dialogInput: {
    backgroundColor: '#26272B',
    borderRadius: 8,
    color: '#FFFFFF',
    fontFamily: 'Nunito_400Regular',
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 14,
  },
  dialogLinkText: {
    color: '#8162FF',
    fontFamily: 'Nunito_700Bold',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 8,
  },
});
