export const assets = {
  scissor: null,
  logoText: null,
  search: null,
  searchLens: null,
  searchHandle: null,
  categoryScissors: null,
  categoryMustache: null,
  categoryRazor: null,
  bannerBackground: require('../../../assets/images/banner_illustration.png'),
  bannerWindow: null,
  bannerStars: null,
  bannerCharacterTwo: null,
  bannerCharacterOne: null,
  bannerTable: null,
  bannerMirror: null,
  scheduleAvatar: null,
  star: null,
  barberOne: require('../../../assets/images/barber_one.png'),
  barberTwo: require('../../../assets/images/barber_two.png'),
  barberThree: require('../../../assets/images/barber_three.png'),
  barberFour: require('../../../assets/images/barber_four.png'),
};
