export const assets = {
  scissor: null,
  logoText: null,
  search: null,
  searchLens: null,
  searchHandle: null,
  categoryScissors: null,
  categoryMustache: null,
  categoryRazor: null,
  bannerBackground: null,
  bannerWindow: null,
  bannerStars: null,
  bannerCharacterTwo: null,
  bannerCharacterOne: null,
  bannerTable: null,
  bannerMirror: null,
  scheduleAvatar: null,
  star: null,
  barberOne: null,
  barberTwo: null,
  barberThree: null,
  barberFour: null,
};
