import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#141518',
  },
  menuOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    zIndex: 10,
  },
  scrollContent: {
    paddingBottom: 24,
  },
  header: {
    backgroundColor: '#141518',
  },
  headerRow: {
    paddingHorizontal: 20,
    paddingVertical: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logo: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 22,
  },
  logoScissor: {
    width: 22,
    height: 22,
    marginRight: 6,
    tintColor: '#8162FF',
  },
  logoText: {
    width: 95,
    height: 18,
  },
  menuButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#141518',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  menuLine: {
    width: 16,
    height: 2,
    borderRadius: 2,
    backgroundColor: '#FFFFFF',
  },
  divider: {
    height: 1,
    backgroundColor: '#26272B',
  },
  greeting: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 12,
    gap: 4,
  },
  greetingTitle: {
    fontSize: 20,
    color: '#FFFFFF',
    fontFamily: 'Nunito_400Regular',
    lineHeight: 24,
  },
  greetingName: {
    fontFamily: 'Nunito_700Bold',
  },
  greetingSubtitle: {
    fontSize: 14,
    color: '#FFFFFF',
    opacity: 0.8,
    fontFamily: 'Nunito_400Regular',
  },
  searchRow: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  searchInputWrapper: {
    flex: 1,
    height: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#26272B',
    backgroundColor: '#1A1B1F',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  searchInput: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'Nunito_400Regular',
    paddingVertical: 0,
  },
  searchButton: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#8162FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchIconBox: {
    width: 20,
    height: 20,
  },
  searchLens: {
    position: 'absolute',
    top: '12.5%',
    left: '12.5%',
    right: '20.83%',
    bottom: '20.83%',
  },
  searchHandle: {
    position: 'absolute',
    top: '69.58%',
    left: '69.58%',
    right: '12.5%',
    bottom: '12.5%',
  },
  categoryRow: {
    paddingHorizontal: 20,
    paddingTop: 24,
    gap: 12,
  },
  categoryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#26272B',
    backgroundColor: '#1A1B1F',
    gap: 10,
  },
  categoryIcon: {
    width: 16,
    height: 16,
  },
  categoryText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'Nunito_700Bold',
  },
  banner: {
    marginTop: 24,
    marginHorizontal: 20,
    height: 150,
    borderRadius: 10,
    backgroundColor: '#221C3D',
    overflow: 'hidden',
  },
  bannerContent: {
    position: 'absolute',
    left: 27,
    top: 41,
  },
  bannerTitle: {
    fontSize: 22,
    color: '#FFFFFF',
    fontFamily: 'Nunito_700Bold',
    lineHeight: 26,
  },
  bannerSubtitle: {
    marginTop: 4,
    fontSize: 14,
    color: '#FFFFFF',
    fontFamily: 'Nunito_300Light',
  },
  bannerArt: {
    position: 'absolute',
    left: 165,
    top: -44,
    width: 240,
    height: 240,
  },
  bannerBackground: {
    position: 'absolute',
    left: '10.11%',
    right: '9.22%',
    top: '10.11%',
    bottom: '14.71%',
  },
  bannerWindow: {
    position: 'absolute',
    left: '9.24%',
    right: '9.81%',
    top: '8.78%',
    bottom: '37.42%',
  },
  bannerStars: {
    position: 'absolute',
    left: '47.64%',
    right: '15.45%',
    top: '17.02%',
    bottom: '39.35%',
  },
  bannerCharacterTwo: {
    position: 'absolute',
    left: '18.46%',
    right: '25.74%',
    top: '15.69%',
    bottom: '26.26%',
  },
  bannerCharacterOne: {
    position: 'absolute',
    left: '23.38%',
    right: '20.32%',
    top: '27.94%',
    bottom: '15.42%',
  },
  bannerTable: {
    position: 'absolute',
    left: '13.03%',
    right: '13.43%',
    top: '84.57%',
    bottom: '15.43%',
  },
  bannerMirror: {
    position: 'absolute',
    left: '46.64%',
    right: '12.93%',
    top: '65.74%',
    bottom: '8.79%',
  },
  section: {
    paddingHorizontal: 20,
    paddingTop: 24,
    gap: 12,
  },
  sectionTitle: {
    color: '#838896',
    fontSize: 12,
    fontFamily: 'Nunito_700Bold',
  },
  scheduleCard: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#26272B',
    backgroundColor: '#1A1B1F',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  scheduleInfo: {
    flex: 1,
    padding: 12,
    gap: 12,
  },
  statusPill: {
    alignSelf: 'flex-start',
    backgroundColor: '#221C3D',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 100,
  },
  statusText: {
    color: '#8162FF',
    fontSize: 12,
    fontFamily: 'Nunito_700Bold',
  },
  scheduleDetails: {
    gap: 8,
  },
  scheduleTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: 'Nunito_700Bold',
  },
  scheduleBarber: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  scheduleAvatarWrapper: {
    width: 24,
    height: 24,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#26272B',
  },
  scheduleAvatar: {
    width: 24,
    height: 24,
  },
  scheduleBarberName: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'Nunito_400Regular',
  },
  scheduleDate: {
    width: 106,
    borderLeftWidth: 1,
    borderLeftColor: '#26272B',
    paddingHorizontal: 20,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  scheduleMonth: {
    color: '#FFFFFF',
    fontSize: 12,
    fontFamily: 'Nunito_400Regular',
  },
  scheduleDay: {
    color: '#FFFFFF',
    fontSize: 24,
    fontFamily: 'Nunito_400Regular',
    lineHeight: 28,
  },
  scheduleTime: {
    color: '#FFFFFF',
    fontSize: 12,
    fontFamily: 'Nunito_400Regular',
  },
  cardsRow: {
    gap: 16,
    paddingRight: 20,
  },
  barberCard: {
    width: 167,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#26272B',
    backgroundColor: '#1A1B1F',
    overflow: 'hidden',
  },
  barberImageWrapper: {
    paddingTop: 4,
    paddingHorizontal: 4,
    paddingBottom: 8,
  },
  barberImage: {
    width: 159,
    height: 159,
    borderRadius: 16,
  },
  ratingBadge: {
    position: 'absolute',
    left: 8,
    top: 8,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 16,
    backgroundColor: 'rgba(34, 28, 61, 0.7)',
    gap: 4,
  },
  ratingStar: {
    width: 12,
    height: 12,
  },
  ratingText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontFamily: 'Nunito_700Bold',
  },
  barberInfo: {
    paddingHorizontal: 12,
    paddingBottom: 12,
    gap: 12,
  },
  barberTextBlock: {
    gap: 4,
  },
  barberName: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: 'Nunito_700Bold',
  },
  barberAddress: {
    color: '#838896',
    fontSize: 12,
    fontFamily: 'Nunito_400Regular',
    lineHeight: 16,
  },
  reserveButton: {
    borderRadius: 10,
    backgroundColor: '#26272B',
    alignItems: 'center',
    paddingVertical: 8,
  },
  reserveButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'Nunito_700Bold',
  },
  footer: {
    marginTop: 48,
    backgroundColor: '#1A1B1F',
    paddingHorizontal: 20,
    paddingVertical: 24,
    alignItems: 'center',
  },
  footerText: {
    color: '#838896',
    fontSize: 12,
    fontFamily: 'Nunito_400Regular',
  },
  footerTextBold: {
    fontFamily: 'Nunito_700Bold',
    color: '#838896',
  },
});
